language: python

python:
  - "2.7"

install_script: pip install -r requirements.txt

# Dummy command until we have real tests
script: true

branches:
  only:
    # Travis will build annotated tags as branches unless we restrict to this
    - 23-travis-deploy

deploy:
  provider: heroku
  api_key:
    secure: iVL9lU8sa9Hiu+IloQRVer19Q9yvcUd731MwKBKkObsx/D80o2hmrU0YniSHuow6tz0mqzQrh8KIbYwdEQ6UDgSBXlAddxEb7S/AR2Xu+Db398Ec+CbfopdYVxDA0YKVJ/Anw0PXPfmZ0fZJaNK4nAMPU953Q71NM96ZXDVV3+Q=
  app:
    23-travis-deploy: gittip-building-test
  on:
    repo: patcon/building.gittip.com
    branch: 23-travis-deploy
