language: python

python:
  - "2.7"

install_script: pip install -r requirements.txt

# Dummy command until we have real tests
script: true

branches:
  only:
    # Travis will build annotated tags as branches unless we restrict to this
    - 23-travis-deploy

deploy:
  provider: heroku
  api_key:
    secure: E8P42osrixrUqtZ+jiPiYgGCI/mf3Lnjf4d5a7X9wCVOhk8g+mdCBZkUXU+rwHaO2tgrAnKXIDSrriU4P9zYAT4Hfg/hEa3DN9XA5NCj96pm5+gNVt6L8BUFM57Yfb2ZjH8FUf9k7ePRda5jC3B7oGBQv+sI7XHH6IdaiEWXmBw=
  app:
    23-travis-deploy: gittip-building-test
  on:
    repo: patcon/building.gittip.com
    branch: 23-travis-deploy

before_deploy:
  - cd www/repos && git clone https://github.com/gittip/www.gittip.com.git
  - cd www/repos && git clone https://github.com/gittip/gttp.co.git
  - cd www/repos && git clone https://github.com/gittip/Gittip-Everywhere.git
